apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 80        # External port exposed to the outside
      targetPort: 8080  # The port your app is running on in the container
  type: LoadBalancer  # Use LoadBalancer to expose externally (NodePort can also be used)
